server:
  tomcat:
    max-threads: 10
    min-threads: 10
  port: 4444
  
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource

    # ############################数据库驱动#########################
    # ############################数据库驱动#########################
    # postgresql
    driverClassName: org.postgresql.Driver
    # mysql5.8以下版本
    # driverClassName: com.mysql.jdbc.Driver
    # mysql5.8以上版本或mariadb
    # driverClassName: com.mysql.cj.jdbc.Driver
    # ############################数据库驱动#########################
    # ############################数据库驱动#########################

    url: jdbc:postgresql://hgd11:5432/postgres
    username: postgres
    password: root

  fastjson:
    time-zone: GMT+8
    data-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    
# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml

logging:
  level:
    com.hgd: debug

# 配置classpath下template目录内，哪个模板不参与代码生成，多个模板之间用逗号隔开，如biz.java,controller.java
vm-template:
  ignore: index.js,index.vue

# #######################公共属性##############################
# #######################公共属性##############################
# 包名
package:
  basePackage: cn.hgd11.ai
  # biz层包名，如biz,service
  bizPackage: service
  # entity层包名，如entity,model
  entityPackage: model
  # controller层包名，如controller,rest
  controllerPackage: controller
  # mapper层包名，如mapper,dao
  mapperPackage: mapper
  # mapper映射文件夹名称，如mapper
  mapperXMLFolder: mapper

#作者
author: 尚村山夫
email: 13821211755@163.com

#表前错误的Unicode字符串!
tablePrefix:
#前端模块前缀
mainModule: auth

# 公共Biz
commonBusinessBiz: cn.hgd11.common.biz.BusinessBiz
# 公共Controller
commonController: cn.hgd11.common.controller.BaseController
# 公共Mapper
commonMapper: cn.hgd11.common.mapper.CommonMapper

# #######################公共属性##############################
# #######################公共属性##############################
